### ISSUE TITLE
Support autofix

### ISSUE THREAD

**Issue by hrb90** [txchen/eslint-plugin-riot#11]
We're setting up an eslint config for a Riot project at work and need autofix support for how we want to use the linter.

What we'd need to do is translate the source position of every error in the processed code into the source position of every error in the original code. We need two things for this; the source position at the beginning of the script, and the number of characters we're getting rid of at every line when we dedent. The first part is easy --- we can just capture `parser.startIndex` the first time we hit the `onText` callback inside the script tag. The dedenting part is the tough bit --- it appears that in general we're not removing the same number of characters from each line in a given file. 

After a few hacks at the problem, we ended up just removing the dedenting step, since that doesn't break any of our linter rules; you can see what that looks like [at our forked repo](https://github.com/systemsthinkinginstitute/prettier-linter-riot). It's working well enough for us, but I didn't want to open a PR that would remove some functionality and probably break people's linters :smile:

Thanks!

**Comment by txchen** [comment]
@hrb90 Thanks for issue! However I stopped using riot for a few years and I am not planning to move back. So this project is actually not maintained anymore. 

Maybe I should mark this as deprecated. Does riot has the official eslint solution now? I think they should provide that.

Sorry that I cannot help on this.
