### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by vonWolfehaus** [txchen/eslint-plugin-riot#2]
Thanks for writing this extractor! I was wondering [why you `return`](https://github.com/txchen/eslint-plugin-riot/blob/master/src/extract.js#L23) if the script type isn't es6. Is there some linting quirk that ends up happening or something? Or can you simply remove the type and lint the js as usual?

**Comment by txchen** [comment]
@vonWolfehaus I thought eslint is designed for es6, but not es5. Besides, riot's default syntax is es5 + tiny es6 like method declaration, I thought it is not going to work. Maybe I am wrong?

**Comment by vonWolfehaus** [comment]
No, [eslint only lints es5 by default](http://eslint.org/docs/user-guide/configuring#specifying-language-options) - you need a plugin to lint es6+. Riot does use the es6 way of declaring functions, but it is optional. So instead of requiring it, it seems prudent to let developers choose whichever linting rules they want. ESLint was designed to be open-ended and not force any particular version of JS - it all depends on the plugins you use with it.

Didn't you try it without that early `return` and a default eslint installation? What happened?

**Comment by txchen** [comment]
I don't remember I use some plugin to let eslint lint es6:)
I will have a try to see what will happen, thanks for the suggestion.

**Comment by txchen** [comment]
@vonWolfehaus 

This is my test result:

script (copied from riot official site):

```
this.items = []

add(e) {
  var input = e.target[0]
  this.items.push(input.value)
  input.value = ''
}
```

Then use eslint to lint it, I got:

```
/Users/txchen/localcode/eslinttest/riotes5.js
  3:9  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)
```

So I think eslint by default does not support riot's mini es6 syntax, which is not a standard syntax. http://riotjs.com/guide/#tag-syntax

**Comment by vonWolfehaus** [comment]
I didn't expect it to. People will have to use pure es5 with riot in order to use eslint, which I think is the way to go. Otherwise they can add the es6 plugin.

In the meantime, can you add that function syntax to your plugin as a rule? That would solve the issue and make it work out of the box without having to use extra plugins (eg es6).

**Comment by txchen** [comment]
I don't think a rule can solve the problem, it should be parser problem. Both eslint default parser 'esprima' and 'babel-eslint' does not support riot's mini es6 syntax. And honestly I don't think I have bandwidth to create a parser for that, sorry.

BTW, in the README of this plugin, it is called out that this only support 'es6' script type.

**Comment by vonWolfehaus** [comment]
I know your plugin only supports es6, that's why I created this issue :) Thanks for your time anyway though.
