### ISSUE TITLE
Support plain <script> tags?

### ISSUE THREAD

**Issue by avimar** [txchen/eslint-plugin-riot#6]
I use `<script></script>` to ensure the parser knows where the js starts, but your setting seems to require one of `'es6', 'babel', 'javascript'`.

If you replace `!attrs.type` with `attrs.type` then assumes 'allows' missing types should be sent to the linter, here: https://github.com/txchen/eslint-plugin-riot/blob/master/src/extract.js#L22

Is this a change you'd make?

(I'm still not sure if this fits in my flow -- I'm using many dirty globals, different than my nodejs code, so I need a totally separate eslint config.)

**Comment by avimar** [comment]
Unless you're using `es6`, it seems https://github.com/BenoitZugmeyer/eslint-plugin-html supports it... and it doesn't look like there's any riot-specific lint functions.

**Comment by txchen** [comment]
The reason I required es6 was: linter cannot understand riot's mini-es6 syntax. When we use 'es6', it is standard.
