### ISSUE TITLE
Riot ES6 syntax produces parsing error

### ISSUE THREAD

**Issue by sanbor** [txchen/eslint-plugin-riot#7]
I'm trying to make this plugin work but I keep getting parser error.

```
% ./node_modules/eslint/bin/eslint.js file.tag

file.tag
  64:20  error  Parsing error: Unexpected token )
```

.eslintrc
```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "node": true
    },
    "plugins": ["riot"],
    "extends": "eslint:recommended",
    "rules": {
        "no-console": 1,
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-trailing-spaces": 2
    }
}
```

file.tag
```
<script type="es6">
this.likePost = () => {
riot.control.trigger(riot.VE.LIKE_POST, opts.data.postId)
}
</script>
```

**Comment by txchen** [comment]
Sorry, this does not support riot's mini es6 syntax.

**Comment by sanbor** [comment]
Thanks for your quick reply. I'd like to mention that this code was extracted from the readme. Why the example in the readme doesn't work? What this plugin does that https://github.com/BenoitZugmeyer/eslint-plugin-html doesn't?

**Comment by txchen** [comment]
Sorry I was reading too fast. I thought you were talking about riot's `mini es6` syntax.
I am looking into it now.

This plugin's logic: extract the js part from .tag, and invoke eslint. If you are using .tag in riot, this might be useful. When I started this repo, I was not aware of the plugin you mentioned :)

**Comment by txchen** [comment]
I just tried with your example. I think with the latest eslint, you need to:

1) npm install babel-eslint@6 --save-dev
2) set `"parser": "babel-eslint"` in .eslintrc, so that eslint can understand es6 syntax.

**Comment by sanbor** [comment]
That worked! Thank you so much :). Should I do a PR with this information to make the basic example work out of the box?

**Comment by txchen** [comment]
@sanbor It would be nice if you can do the PR :)
