### ISSUE TITLE
Is it possible to add eslint even when type is empty?

### ISSUE THREAD

**Issue by t4y3** [txchen/eslint-plugin-riot#8]
It occurs when compiling with rollup + buble

Sample.
https://github.com/t4y3/example-riot-eslint

**Comment by txchen** [comment]
@t4y3 I haven't touched this lib for a while, and I don't have bandwidth to continue maintaining this one. If you can submit a PR, that will be awesome.

**Comment by gitbreaker222** [comment]
the merged PR indicates, that this issue is solved. Can you confirm @t4y3 ?

**Comment by t4y3** [comment]
Thank you for fixing. confirmed!
